DROP DATABASE IF EXISTS `test_score_management`;
CREATE DATABASE `test_score_management`;
USE `test_score_management`;

CREATE TABLE Student(
IdHS VARCHAR(20) PRIMARY KEY,
NameHS VARCHAR(50),
DateOfBirth DATETIME,
Class VARCHAR(20),
GT VARCHAR(20)
);

CREATE TABLE Subjects(
Id VARCHAR(20) PRIMARY KEY,
Name VARCHAR(50)
);

CREATE TABLE Transcript(
IdHS VARCHAR(20),
IdMH VARCHAR(20),
Testday DATETIME,
PRIMARY KEY(IdHS,IdMH),
FOREIGN KEY(IdHS) REFERENCES Student(IdHS),
FOREIGN KEY(IdMH) REFERENCES Subjects(IdMH)
);

CREATE TABLE Teacher(
IdGV VARCHAR(20) PRIMARY KEY,
NameGV VARCHAR(20),
SDT VARCHAR(10)
);

ALTER TABLE Subjects ADD  IdGV VARCHAR(20);
ALTER TABLE Subjects ADD  CONSTRAINT FK_IdGV FOREIGN KEY (IdGV) REFERENCES Teacher(IdGV)  ;